name: 'Publish to GH Pages'
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: '17'

      - name: Build dist folder
        run: npm run build

      - name: Deploy dist to gh-pages
        run: npm run deploy
